// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.vlad.supportcenter.dto;

import java.io.Serializable;

privileged aspect NewTicketDTO_Roo_Serializable {
    
    declare parents: NewTicketDTO implements Serializable;
    
}
