// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.vlad.supportcenter.dto;

import de.vlad.supportcenter.model.SupportCategory;
import java.lang.Long;
import java.lang.String;
import java.util.Set;

privileged aspect SupportAgentDTO_Roo_JavaBean {
    
    public Long SupportAgentDTO.getId() {
        return this.id;
    }
    
    public void SupportAgentDTO.setId(Long id) {
        this.id = id;
    }
    
    public String SupportAgentDTO.getDisplayName() {
        return this.displayName;
    }
    
    public void SupportAgentDTO.setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    
    public String SupportAgentDTO.getEmail() {
        return this.email;
    }
    
    public void SupportAgentDTO.setEmail(String email) {
        this.email = email;
    }
    
    public String SupportAgentDTO.getPassword() {
        return this.password;
    }
    
    public void SupportAgentDTO.setPassword(String password) {
        this.password = password;
    }
    
    public String SupportAgentDTO.getConfirmPassword() {
        return this.confirmPassword;
    }
    
    public void SupportAgentDTO.setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }
    
    public boolean SupportAgentDTO.isActive() {
        return this.active;
    }
    
    public void SupportAgentDTO.setActive(boolean active) {
        this.active = active;
    }
    
    public Set<SupportCategory> SupportAgentDTO.getAdminCategories() {
        return this.adminCategories;
    }
    
    public void SupportAgentDTO.setAdminCategories(Set<SupportCategory> adminCategories) {
        this.adminCategories = adminCategories;
    }
    
    public boolean SupportAgentDTO.isChatPermission() {
        return this.chatPermission;
    }
    
    public void SupportAgentDTO.setChatPermission(boolean chatPermission) {
        this.chatPermission = chatPermission;
    }
    
}
