// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.vlad.supportcenter.model;

import java.io.Serializable;

privileged aspect Locale_Roo_Serializable {
    
    declare parents: Locale implements Serializable;
    
}
