// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.vlad.supportcenter.model;

import java.lang.String;

privileged aspect SupportAgent_Roo_ToString {
    
    public String SupportAgent.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AdminCategories: ").append(getAdminCategories() == null ? "null" : getAdminCategories().size()).append(", ");
        sb.append("DisplayName: ").append(getDisplayName()).append(", ");
        sb.append("Email: ").append(getEmail()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Password: ").append(getPassword()).append(", ");
        sb.append("Portal: ").append(getPortal()).append(", ");
        sb.append("Active: ").append(isActive()).append(", ");
        sb.append("ChatEnabled: ").append(isChatEnabled()).append(", ");
        sb.append("ChatPermission: ").append(isChatPermission());
        return sb.toString();
    }
    
}
