// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.vlad.supportcenter.model;

import de.vlad.supportcenter.model.SupportCategory;
import java.util.Set;

privileged aspect SupportAgent_Roo_JavaBean {
    
    public Set<SupportCategory> SupportAgent.getAdminCategories() {
        return this.adminCategories;
    }
    
    public void SupportAgent.setAdminCategories(Set<SupportCategory> adminCategories) {
        this.adminCategories = adminCategories;
    }
    
    public boolean SupportAgent.isChatEnabled() {
        return this.chatEnabled;
    }
    
    public void SupportAgent.setChatEnabled(boolean chatEnabled) {
        this.chatEnabled = chatEnabled;
    }
    
    public boolean SupportAgent.isChatPermission() {
        return this.chatPermission;
    }
    
    public void SupportAgent.setChatPermission(boolean chatPermission) {
        this.chatPermission = chatPermission;
    }
    
}
